// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/auth0': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/auth0').default>>>>
    }
    '/api/auth/callback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/callback.post').default>>>>
    }
    '/api/auth/login': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.get').default>>>>
    }
    '/api/auth/logout-complete': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout-complete.get').default>>>>
    }
    '/api/auth/logout': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.get').default>>>>
    }
    '/api/behavior-template/plural': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/behavior-template/plural.get').default>>>>
    }
    '/api/behavior/get/behavior-template': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/behavior/get/behavior-template.get').default>>>>
    }
    '/api/behavior/get/plural': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/behavior/get/plural.get').default>>>>
    }
    '/api/behavior/get/singular': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/behavior/get/singular.get').default>>>>
    }
    '/api/behavior/post/singular': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/behavior/post/singular.post').default>>>>
    }
    '/api/session/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/create.post').default>>>>
    }
    '/api/session/retrieve': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/retrieve.get').default>>>>
    }
    '/api/user/archive/employee': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/archive/employee.put').default>>>>
    }
    '/api/user/archive/student': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/archive/student.put').default>>>>
    }
    '/api/user/create/employee': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/create/employee.post').default>>>>
    }
    '/api/user/create/student': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/create/student.post').default>>>>
    }
    '/api/user/get/employee': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/get/employee.get').default>>>>
    }
    '/api/user/get/employeeNames': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/get/employeeNames.get').default>>>>
    }
    '/api/user/get/employees': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/get/employees.get').default>>>>
    }
    '/api/user/get/student': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/get/student.get').default>>>>
    }
    '/api/user/get/students': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/get/students.get').default>>>>
    }
    '/api/user/update/employee': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/update/employee.put').default>>>>
    }
    '/api/user/update/student': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/update/student.put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}